# Generated by Django 5.2 for TaskFlow
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="Nome")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="projects", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160, verbose_name="Título")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("status", models.CharField(choices=[("todo", "A fazer"), ("doing", "Em andamento"), ("done", "Concluída")], default="todo", max_length=10, verbose_name="Status")),
                ("priority", models.CharField(choices=[("low", "Baixa"), ("medium", "Média"), ("high", "Alta")], default="medium", max_length=10, verbose_name="Prioridade")),
                ("due_date", models.DateField(blank=True, null=True, verbose_name="Prazo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="tasks.project")),
            ],
        ),
    ]
